config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'order_comments/new'

  get 'comments/new'

  get 'sessions/new'

  root to: 'sessions#redirect_to_foodcoop', as: nil

  scope '/:foodcoop' do
    use_doorkeeper

    # Root path
    root to: 'home#index'

    ########### Sessions

    get   '/login' => 'sessions#new', as: 'login'
    get   '/logout' => 'sessions#destroy', as: 'logout'
    get   '/login/forgot_password' => 'login#forgot_password', as: :forgot_password
    post  '/login/reset_password' => 'login#reset_password', as: :reset_password
    get   '/login/new_password' => 'login#new_password', as: :new_password
    patch '/login/update_password' => 'login#update_password', as: :update_password
    match '/login/accept_invitation/:token' => 'login#accept_invitation', as: :accept_invitation, via: %i[get post]
    resources :sessions, only: %i[new create destroy]

    get '/foodcoop.css' => 'styles#foodcoop', as: 'foodcoop_css'

    ########### User specific

    get   '/home/profile', as: 'my_profile'
    get   '/home/reference_calculator'
    patch '/home/update_profile', as: 'update_profile'
    get   '/home/ordergroup' => 'home#ordergroup', as: 'my_ordergroup'
    post  '/home/cancel_membership' => 'home#cancel_membership', as: 'cancel_membership'

    ############ Orders, ordering

    resources :orders do
      member do
        post :finish
        post :add_comment
        post :send_result_to_supplier

        get :receive
        post :receive

        get :receive_on_order_article_create
        get :receive_on_order_article_update
      end

      resources :order_articles
    end

    resources :pickups, only: [:index] do
      post :document, on: :collection
    end

    resources :group_orders do
      get :archive, on: :collection
    end

    resources :group_order_articles

    resources :order_comments, only: %i[new create]

    ############ Foodcoop orga

    resources :invites, only: %i[new create]

    resources :tasks do
      collection do
        get :user
        get :archive
        get :workgroup
      end
      member do
        post :accept
        post :reject
        post :set_done
      end
    end

    namespace :foodcoop do
      root to: 'users#index'

      resources :users, only: [:index]

      resources :ordergroups, only: [:index]

      resources :workgroups, only: %i[index edit update]
    end

    ########### Article management

    resources :stock_takings do
      collection do
        get :new_on_stock_article_create
      end
    end

    resources :stock_articles, controller: 'stockit' do
      get :copy
      collection do
        get :derive

        get :index_on_stock_article_create
        get :index_on_stock_article_update

        get :show_on_stock_article_update
      end
    end

    resources :suppliers do
      get :shared_suppliers, on: :collection

      resources :deliveries do
        collection do
          post :add_stock_change

          get :form_on_stock_article_create
          get :form_on_stock_article_update
        end
      end

      resources :articles do
        get :copy
        collection do
          post :update_selected
          get :edit_all
          post :update_all
          get :upload
          post :parse_upload
          post :create_from_upload
          get :shared
          get :import
          post :sync
          post :update_synchronized
        end
      end
    end

    resources :article_categories

    ########### Finance

    namespace :finance do
      root to: 'base#index'

      resources :order, controller: 'balancing', path: 'balancing' do
        member do
          get :update_summary
          get :edit_note
          put :update_note
          get :edit_transport
          put :update_transport

          get :confirm
          post :close
          patch :close_direct

          get :new_on_order_article_create
          get :new_on_order_article_update
        end

        post :close_all_direct_with_invoice, on: :collection
      end

      resources :invoices do
        get :form_on_supplier_id_change, on: :collection
        get :unpaid, on: :collection
        delete 'delete_attachment/:attachment_id', to: 'invoices#delete_attachment', as: 'delete_attachment', on: :member
      end

      resources :links, controller: 'financial_links', only: %i[create show] do
        collection do
          get :incomplete
        end
        member do
          get :index_bank_transaction
          put 'bank_transactions/:bank_transaction', action: 'add_bank_transaction', as: 'add_bank_transaction'
          delete 'bank_transactions/:bank_transaction', action: 'remove_bank_transaction', as: 'remove_bank_transaction'

          get :index_financial_transaction
          put 'financial_transactions/:financial_transaction', action: 'add_financial_transaction',
                                                               as: 'add_financial_transaction'
          delete 'financial_transactions/:financial_transaction', action: 'remove_financial_transaction',
                                                                  as: 'remove_financial_transaction'

          get :index_invoice
          put 'invoices/:invoice', action: 'add_invoice', as: 'add_invoice'
          delete 'invoices/:invoice', action: 'remove_invoice', as: 'remove_invoice'

          get :new_financial_transaction
          post :create_financial_transaction
        end
      end

      resources :ordergroups, only: [:index] do
        resources :financial_transactions, as: :transactions
      end
      resources :financial_transactions, as: :foodcoop_financial_transactions, path: 'foodcoop/financial_transactions',
                                         only: %i[index new create]
      get :transactions, controller: :financial_transactions, action: :index_collection
      delete 'transactions/:id', controller: :financial_transactions, action: :destroy, as: :transaction

      get 'transactions/new_collection' => 'financial_transactions#new_collection', as: 'new_transaction_collection'
      post 'transactions/create_collection' => 'financial_transactions#create_collection',
           as: 'create_transaction_collection'

      resources :bank_accounts, only: [:index] do
        member do
          get :assign_unlinked_transactions
          get :import
          post :import
        end

        resources :bank_transactions, as: :transactions
      end

      resources :bank_transactions, only: %i[index show]
    end

    ########### Administration

    namespace :admin do
      root to: 'base#index'

      resources :finances, only: [:index] do
        get :update_bank_accounts, on: :collection
        get :update_bank_gateways, on: :collection
        get :update_transaction_types, on: :collection
        get :update_supplier_categories, on: :collection
      end

      resources :bank_accounts
      resources :bank_gateways
      resources :financial_transaction_classes
      resources :financial_transaction_types
      resources :supplier_categories

      resources :users do
        post :restore, on: :member
        post :sudo, on: :member
      end

      resources :workgroups do
        get :memberships, on: :member
      end

      resources :ordergroups do
        get :memberships, on: :member
      end

      resources :mail_delivery_status, only: %i[index show destroy] do
        delete :index, on: :collection, action: :destroy_all
      end

      resource :config, only: %i[show update] do
        get :list
      end
    end

    ############## API

    namespace :api do
      namespace :v1 do
        resource :config, only: [:show]
        resource :navigation, only: [:show]

        namespace :user do
          root to: 'users#show'
          get :financial_overview, to: 'ordergroup#financial_overview'
          resources :financial_transactions, only: %i[index show create]
          resources :group_order_articles
        end

        resources :financial_transaction_classes, only: %i[index show]
        resources :financial_transaction_types, only: %i[index show]
        resources :financial_transactions, only: %i[index show]
        resources :orders, only: %i[index show]
        resources :order_articles, only: %i[index show]
        resources :group_order_articles
        resources :article_categories, only: %i[index show]
      end
    end

    ############## The rest

    resources :users, only: [:index]
  end # End of /:foodcoop scope
end
# rubocop:enable Metrics/BlockLength

app/controllers/admin/ordergroups_controller.rb
class Admin::OrdergroupsController < Admin::BaseController
  inherit_resources

  def index
    @ordergroups = Ordergroup.undeleted.sort_by_param(params['sort'])

    if request.format.csv?
      send_data OrdergroupsCsv.new(@ordergroups).to_csv, filename: 'ordergroups.csv',
                                                         type: 'text/csv'
    end

    # if somebody uses the search field:
    @ordergroups = @ordergroups.where('name LIKE ?', "%#{params[:query]}%") if params[:query].present?

    @ordergroups = @ordergroups.page(params[:page]).per(@per_page)
  end

  def destroy
    @ordergroup = Ordergroup.find(params[:id])
    @ordergroup.mark_as_deleted
    redirect_to admin_ordergroups_url, notice: t('.notice')
  rescue StandardError => e
    redirect_to admin_ordergroups_url, alert: t('.error')
  end
end

app/controllers/api/v1/user/ordergroup_controller.rb
class Api::V1::User::OrdergroupController < Api::V1::BaseController
  before_action -> { doorkeeper_authorize! 'finance:user' }, only: [:financial_overview]

  def financial_overview
    ordergroup = Ordergroup.include_transaction_class_sum.find(current_ordergroup.id)

    render json: {
      financial_overview: {
        account_balance: ordergroup.account_balance.to_f,
        available_funds: ordergroup.get_available_funds.to_f,
        financial_transaction_class_sums: FinancialTransactionClass.sorted.map do |c|
          {
            id: c.id,
            name: c.display,
            amount: ordergroup["sum_of_class_#{c.id}"].to_f
          }
        end
      }
    }
  end
end

app/controllers/finance/ordergroups_controller.rb
class Finance::OrdergroupsController < Finance::BaseController
  def index
    m = /^(?<col>name|sum_of_class_\d+)(?<reverse>_reverse)?$/.match params['sort']
    if m
      sort = m[:col]
      sort += ' DESC' if m[:reverse]
    else
      sort = 'name'
    end

    @ordergroups = Ordergroup.undeleted.order(sort)
    @ordergroups = @ordergroups.include_transaction_class_sum
    @ordergroups = @ordergroups.where('groups.name LIKE ?', "%#{params[:query]}%") unless params[:query].nil?
    @ordergroups = @ordergroups.page(params[:page]).per(@per_page)

    @total_balances = FinancialTransactionClass.sorted.each_with_object({}) do |transaction_class, total_balances|
      total_balances[transaction_class.id] = @ordergroups.reduce(0) { |sum, o| o["sum_of_class_#{transaction_class.id}"] + sum }
    end
  end
end

app/controllers/foodcoop/ordergroups_controller.rb
class Foodcoop::OrdergroupsController < ApplicationController
  def index
    @ordergroups = Ordergroup.undeleted.sort_by_param(params['sort'])

    @ordergroups = @ordergroups.where('name LIKE ?', "%#{params[:name]}%") if params[:name].present? # Search by name

    @ordergroups = @ordergroups.active if params[:only_active] # Select only active groups

    @ordergroups = @ordergroups.page(params[:page]).per(@per_page)

    respond_to do |format|
      format.html # index.html.erb
      format.js { render layout: false }
    end
  end
end

app/helpers/admin/ordergroups_helper.rb
module Admin::OrdergroupsHelper
  def ordergroup_members_title(ordergroup)
    s = ''
    s += ordergroup.users.map(&:name).join(', ') if ordergroup.users.any?
    s += "\n" + Ordergroup.human_attribute_name(:contact) + ': ' + ordergroup.contact_person if ordergroup.contact_person.present?
    s
  end
end

app/helpers/finance/ordergroups_helper.rb
module Finance::OrdergroupsHelper
end

app/views/admin/ordergroups/_form.html.haml
- unless @ordergroup.new_record? || FoodsoftConfig[:disable_invite]
  %p= t('.first_paragraph', url: link_to(t('.here'), new_invite_path(id: @ordergroup.id), remote: true)).html_safe
= simple_form_for [:admin, @ordergroup] do |f|
  - captured = capture do
    = f.input :contact_person
    = f.input :contact_phone
    = f.input :contact_address
    = render 'shared/custom_form_fields', f: f, type: :ordergroup
    .fold-line
      = f.input :break_start, as: :date_picker, label: Ordergroup.human_attribute_name('break')
      = f.input :break_end, as: :date_picker, label: Ordergroup.human_attribute_name('break_until')
    - if FoodsoftConfig[:use_apple_points]
      = f.input :ignore_apple_restriction, :label => false, :inline_label => true
  = render 'shared/group_form_fields', f: f, captured: captured
  .form-actions
    = f.button :submit
    = link_to t('ui.or_cancel'), :back

app/views/admin/ordergroups/_ordergroups.html.haml
- if Ordergroup.count > 20
  = items_per_page
= pagination_links_remote @ordergroups
%table.table.table-striped
  %thead
    %tr
      %th= sort_link_helper heading_helper(Ordergroup, :name), "name"
      %th= sort_link_helper heading_helper(Ordergroup, :user_tokens), "members_count"
      %th= heading_helper Ordergroup, :contact_address
      %th= sort_link_helper heading_helper(Ordergroup, :last_user_activity), "last_user_activity"
      %th= sort_link_helper heading_helper(Ordergroup, :last_order), "last_order"
      %th= t 'ui.actions'
  %tbody
    - for ordergroup in @ordergroups
      %tr{:class => cycle('even','odd', :name => 'groups')}
        %td= link_to ordergroup.name, [:admin, ordergroup]
        %td{title: ordergroup_members_title(ordergroup)}
          %abbr{title: ordergroup_members_title(ordergroup)}= ordergroup.users.size
        %td= link_to_gmaps ordergroup.contact_address
        %td= format_date ordergroup.last_user_activity
        %td= format_date ordergroup.last_order.try(:starts)
        %td
          = link_to t('ui.edit'), edit_admin_ordergroup_path(ordergroup), class: 'btn btn-mini'
          = link_to t('ui.delete'), [:admin, ordergroup], :data => {:confirm => t('ui.confirm_delete', name: ordergroup.name)},
            :method => :delete, class: 'btn btn-mini btn-danger'

app/views/admin/ordergroups/edit.html.haml
- title t '.title'

= render 'form'

app/views/admin/ordergroups/index.html.haml
- title t('.title')

- content_for :actionbar do
  = link_to t('.new_ordergroup'), new_admin_ordergroup_path, class: 'btn btn-primary'
  = link_to url_for(search: params[:q], format: :csv), class: 'btn' do
    = glyph :download
    CSV

- content_for :sidebar do
  %p= t('.first_paragraph', url: link_to(t('.new_ordergroups'), new_admin_ordergroup_path)).html_safe
  %p= t('.second_paragraph', url: link_to(t('.workgroup'), admin_workgroups_path)).html_safe
.well.well-small
  = form_tag admin_ordergroups_path, :method => :get, :remote => true,
    'data-submit-onchange' => true, class: 'form-search' do
    = text_field_tag :query, params[:query], class: 'input-medium search-query',
      placeholder: t('admin.search_placeholder')
#ordergroups
  = render "ordergroups"

app/views/admin/ordergroups/index.js.haml
$('#ordergroups').html('#{escape_javascript(render("ordergroups"))}');

app/views/admin/ordergroups/new.html.haml
- title t '.title'

= render 'form'

app/views/admin/ordergroups/show.html.haml
- title t '.title', name: @ordergroup.name

%section= render 'shared/group', group: @ordergroup
= link_to t('ui.edit'), edit_admin_ordergroup_path(@ordergroup), class: 'btn'
= link_to t('ui.delete'), [:admin, @ordergroup], :data => {:confirm => t('.confirm')}, :method => :delete, class: 'btn btn-danger'