config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'order_comments/new'

  get 'comments/new'

  get 'sessions/new'

  root to: 'sessions#redirect_to_foodcoop', as: nil

  scope '/:foodcoop' do
    use_doorkeeper

    # Root path
    root to: 'home#index'

    ########### Sessions

    get   '/login' => 'sessions#new', as: 'login'
    get   '/logout' => 'sessions#destroy', as: 'logout'
    get   '/login/forgot_password' => 'login#forgot_password', as: :forgot_password
    post  '/login/reset_password' => 'login#reset_password', as: :reset_password
    get   '/login/new_password' => 'login#new_password', as: :new_password
    patch '/login/update_password' => 'login#update_password', as: :update_password
    match '/login/accept_invitation/:token' => 'login#accept_invitation', as: :accept_invitation, via: %i[get post]
    resources :sessions, only: %i[new create destroy]

    get '/foodcoop.css' => 'styles#foodcoop', as: 'foodcoop_css'

    ########### User specific

    get   '/home/profile', as: 'my_profile'
    get   '/home/reference_calculator'
    patch '/home/update_profile', as: 'update_profile'
    get   '/home/ordergroup' => 'home#ordergroup', as: 'my_ordergroup'
    post  '/home/cancel_membership' => 'home#cancel_membership', as: 'cancel_membership'

    ############ Orders, ordering

    resources :orders do
      member do
        post :finish
        post :add_comment
        post :send_result_to_supplier

        get :receive
        post :receive

        get :receive_on_order_article_create
        get :receive_on_order_article_update
      end

      resources :order_articles
    end

    resources :pickups, only: [:index] do
      post :document, on: :collection
    end

    resources :group_orders do
      get :archive, on: :collection
    end

    resources :group_order_articles

    resources :order_comments, only: %i[new create]

    ############ Foodcoop orga

    resources :invites, only: %i[new create]

    resources :tasks do
      collection do
        get :user
        get :archive
        get :workgroup
      end
      member do
        post :accept
        post :reject
        post :set_done
      end
    end

    namespace :foodcoop do
      root to: 'users#index'

      resources :users, only: [:index]

      resources :ordergroups, only: [:index]

      resources :workgroups, only: %i[index edit update]
    end

    ########### Article management

    resources :stock_takings do
      collection do
        get :new_on_stock_article_create
      end
    end

    resources :stock_articles, controller: 'stockit' do
      get :copy
      collection do
        get :derive

        get :index_on_stock_article_create
        get :index_on_stock_article_update

        get :show_on_stock_article_update
      end
    end

    resources :suppliers do
      get :shared_suppliers, on: :collection

      resources :deliveries do
        collection do
          post :add_stock_change

          get :form_on_stock_article_create
          get :form_on_stock_article_update
        end
      end

      resources :articles do
        get :copy
        collection do
          post :update_selected
          get :edit_all
          post :update_all
          get :upload
          post :parse_upload
          post :create_from_upload
          get :shared
          get :import
          post :sync
          post :update_synchronized
        end
      end
    end

    resources :article_categories

    ########### Finance

    namespace :finance do
      root to: 'base#index'

      resources :order, controller: 'balancing', path: 'balancing' do
        member do
          get :update_summary
          get :edit_note
          put :update_note
          get :edit_transport
          put :update_transport

          get :confirm
          post :close
          patch :close_direct

          get :new_on_order_article_create
          get :new_on_order_article_update
        end

        post :close_all_direct_with_invoice, on: :collection
      end

      resources :invoices do
        get :form_on_supplier_id_change, on: :collection
        get :unpaid, on: :collection
        delete 'delete_attachment/:attachment_id', to: 'invoices#delete_attachment', as: 'delete_attachment', on: :member
      end

      resources :links, controller: 'financial_links', only: %i[create show] do
        collection do
          get :incomplete
        end
        member do
          get :index_bank_transaction
          put 'bank_transactions/:bank_transaction', action: 'add_bank_transaction', as: 'add_bank_transaction'
          delete 'bank_transactions/:bank_transaction', action: 'remove_bank_transaction', as: 'remove_bank_transaction'

          get :index_financial_transaction
          put 'financial_transactions/:financial_transaction', action: 'add_financial_transaction',
                                                               as: 'add_financial_transaction'
          delete 'financial_transactions/:financial_transaction', action: 'remove_financial_transaction',
                                                                  as: 'remove_financial_transaction'

          get :index_invoice
          put 'invoices/:invoice', action: 'add_invoice', as: 'add_invoice'
          delete 'invoices/:invoice', action: 'remove_invoice', as: 'remove_invoice'

          get :new_financial_transaction
          post :create_financial_transaction
        end
      end

      resources :ordergroups, only: [:index] do
        resources :financial_transactions, as: :transactions
      end
      resources :financial_transactions, as: :foodcoop_financial_transactions, path: 'foodcoop/financial_transactions',
                                         only: %i[index new create]
      get :transactions, controller: :financial_transactions, action: :index_collection
      delete 'transactions/:id', controller: :financial_transactions, action: :destroy, as: :transaction

      get 'transactions/new_collection' => 'financial_transactions#new_collection', as: 'new_transaction_collection'
      post 'transactions/create_collection' => 'financial_transactions#create_collection',
           as: 'create_transaction_collection'

      resources :bank_accounts, only: [:index] do
        member do
          get :assign_unlinked_transactions
          get :import
          post :import
        end

        resources :bank_transactions, as: :transactions
      end

      resources :bank_transactions, only: %i[index show]
    end

    ########### Administration

    namespace :admin do
      root to: 'base#index'

      resources :finances, only: [:index] do
        get :update_bank_accounts, on: :collection
        get :update_bank_gateways, on: :collection
        get :update_transaction_types, on: :collection
        get :update_supplier_categories, on: :collection
      end

      resources :bank_accounts
      resources :bank_gateways
      resources :financial_transaction_classes
      resources :financial_transaction_types
      resources :supplier_categories

      resources :users do
        post :restore, on: :member
        post :sudo, on: :member
      end

      resources :workgroups do
        get :memberships, on: :member
      end

      resources :ordergroups do
        get :memberships, on: :member
      end

      resources :mail_delivery_status, only: %i[index show destroy] do
        delete :index, on: :collection, action: :destroy_all
      end

      resource :config, only: %i[show update] do
        get :list
      end
    end

    ############## API

    namespace :api do
      namespace :v1 do
        resource :config, only: [:show]
        resource :navigation, only: [:show]

        namespace :user do
          root to: 'users#show'
          get :financial_overview, to: 'ordergroup#financial_overview'
          resources :financial_transactions, only: %i[index show create]
          resources :group_order_articles
        end

        resources :financial_transaction_classes, only: %i[index show]
        resources :financial_transaction_types, only: %i[index show]
        resources :financial_transactions, only: %i[index show]
        resources :orders, only: %i[index show]
        resources :order_articles, only: %i[index show]
        resources :group_order_articles
        resources :article_categories, only: %i[index show]
      end
    end

    ############## The rest

    resources :users, only: [:index]
  end # End of /:foodcoop scope
end
# rubocop:enable Metrics/BlockLength

app/helpers/shared_helper.rb
module SharedHelper
  # provide input_html for password autocompletion
  def autocomplete_flag_to_password_html(password_autocomplete)
    case password_autocomplete
    when true then { autocomplete: 'on' }
    when false then { autocomplete: 'off' }
    when 'store-only' then { autocomplete: 'off', data: { store: 'on' } }
    else {}
    end
  end
end

app/views/shared/_alert_success.haml
.alert.fade.in.alert-success
  %a.close{:href => '#', :data => {:dismiss => 'alert'}}
    = t('ui.marks.close').html_safe
  = t('ui.marks.success').html_safe
  = alert_message

app/views/shared/_article_fields_price.html.haml
.fold-line
  = f.input :price do
    .input-prepend
      %span.add-on= t 'number.currency.format.unit'
      = f.input_field :price, class: 'input-mini'
  = f.input :tax do
    .input-append
      = f.input_field :tax, class: 'input-mini'
      %span.add-on %
.fold-line
  = f.input :deposit do
    .input-prepend
      %span.add-on= t 'number.currency.format.unit'
      = f.input_field :deposit, class: 'input-mini'
  .control-group
    %label.control-label{for: 'article_fc_price'}
      = Article.human_attribute_name(:fc_price)
    .controls.control-text#article_fc_price
      = number_to_currency(f.object.fc_price) rescue nil

-# do this inline, since it's being used in ajax forms only
- field = f.object.class.model_name.to_s.underscore
:javascript
  var form = $('#article_fc_price').closest('form');
  $('##{field}_price, ##{field}_tax, ##{field}_deposit', form).on('change keyup', function() {
    var price = parseFloat($('##{field}_price', form).val());
    var tax = parseFloat($('##{field}_tax', form).val());
    var deposit = parseFloat($('##{field}_deposit', form).val());
    // Article#gross_price and Article#fc_price
    var gross_price = (price + deposit) * (tax / 100 + 1);
    var fc_price = gross_price  * (#{FoodsoftConfig[:price_markup].to_f} / 100 + 1);
    $('#article_fc_price').html($.isNumeric(fc_price) ? I18n.l("currency", fc_price) : '&#133;');
  });

app/views/shared/_article_fields_units.html.haml
-# use the local 'f', or supply 'f_uq' and 'f_unit' for more control (like in balancing)
.fold-line
  = (f_uq rescue f).input :unit_quantity, label: Article.human_attribute_name(:unit),
    input_html: {class: 'input-mini', title: Article.human_attribute_name(:unit_quantity)}
  = (f_unit rescue f).input :unit, label: '&times;'.html_safe,
    input_html: {class: 'input-mini', title: Article.human_attribute_name(:unit)}

app/views/shared/_article_price_info.html.haml
%table.table.table-condensed
  %tr
    %th= t 'activerecord.attributes.article.price'
    %td.numeric= number_to_currency article.price
  %tr
    %th= t 'activerecord.attributes.article.deposit'
    %td.numeric= number_to_currency article.deposit
  %tr
    %th= t 'activerecord.attributes.article.tax'
    %td.numeric= number_to_percentage article.tax
  - unless article.fc_price == article.gross_price
    %tr
      %th= t 'activerecord.attributes.article.fc_share'
      %td.numeric= number_to_currency(article.fc_price-article.gross_price)
  %tr
    %th= t 'activerecord.attributes.article.fc_price'
    %td.numeric= number_to_currency article.fc_price

app/views/shared/_base_errors.haml
.alert.alert-error.alert-block
  %a.close{:href => '#', :data => {:dismiss => 'alert'}}
    = t('ui.marks.close').html_safe
  %ul
    = error_messages.html_safe

app/views/shared/_comments.haml
- comments.each do |comment|
  .comment[comment]
    %strong= comment.user.try(:ordergroup_name)
    %small (#{show_user comment.user} am #{format_time(comment.created_at)}):
    = simple_format(comment.text)

app/views/shared/_custom_form_fields.html.haml
- if FoodsoftConfig[:custom_fields] && FoodsoftConfig[:custom_fields][type]
  = f.simple_fields_for :custom_fields, defaults: { required: false } do |s|
    - FoodsoftConfig[:custom_fields][type].each do |options|
      - options = options.deep_symbolize_keys
      - name = options.delete(:name)
      - value = f.object.settings.custom_fields[name]
      = s.input name, options.deep_merge(input_html: {value:value})

app/views/shared/_group.html.haml
%dl
  %dt= heading_helper(Ordergroup, :description) + ':'
  %dd=h group.description
  - if group.is_a?(Ordergroup) and (@current_user.role_admin? or @current_user.role_finance?)
    %dt= heading_helper(Ordergroup, :contact) + ':'
    %dd=h group.contact
    %dt= heading_helper(Ordergroup, :contact_address) + ':'
    %dd= link_to_gmaps group.contact_address
  - if group.break_start? or group.break_end?
    %dt= heading_helper(Ordergroup, :break) + ':'
    %dd= raw t '.break', start: format_date(group.break_start), end: format_date(group.break_end)
  - if group.is_a?(Workgroup)
    %dt= t('.access') + ':'
    %dd= format_roles(group)
  %dt= heading_helper(Ordergroup, :user_tokens) + ':'
  %dd
    - members = group.users
    = "(#{members.size})"
    = members.collect{|u| show_user(u)}.join(", ")
  - if group.is_a?(Ordergroup) and FoodsoftConfig[:use_apple_points]
    %dt= t '.apple_limit'
    %dd= group.ignore_apple_restriction ? t('.deactivated') : t('.activated')

app/views/shared/_group_form_fields.html.haml
= f.input :name
= f.input :description, as: :text, input_html: {rows: 4}

= captured if defined? captured

= f.input :user_tokens, :as => :string,
  :input_html => { 'data-pre' => f.object.users.map(&:token_attributes).to_json }

- content_for :javascript do
  :javascript
    $(function() {
      $("##{f.object.class.to_s.underscore}_user_tokens").tokenInput("#{users_path(:format => :json)}", {
        crossDomain: false,
        prePopulate: $("##{f.object.class.to_s.underscore}_user_tokens").data("pre"),
        hintText: '#{t('.search_user')}',
        noResultText: '#{t('.user_not_found')}',
        searchingText: '#{t('.search')}',
        theme: 'facebook'
      });
    });

app/views/shared/_open_orders.html.haml
%section
  %h2= t '.title'
  - if ordergroup.not_enough_apples?
    .alert
      = t '.not_enough_apples'
  - orders = Order.open.started
  - unless orders.empty?
    %table.table.table-striped
      %thead
        %tr
          %th= heading_helper Order, :name
          %th= heading_helper Order, :pickup
          %th= heading_helper Order, :ends
          %th= t '.who_ordered'
          %th.numeric= heading_helper GroupOrder, :price
      %tbody
        - total = 0
        - orders.each do |order|
          %tr
            %td= link_to_ordering(order)
            %td= format_date(order.pickup) unless order.pickup.nil?
            %td= format_time(order.ends) unless order.ends.nil?
            - if group_order = order.group_order(ordergroup)
              - total += group_order.price
              %td= "#{show_user group_order.updated_by} (#{format_time(group_order.updated_on)})"
              %td.numeric
                = link_to_ordering(order, show: true) do
                  = number_to_currency(group_order.price)
            - else
              %td{:colspan => 2}
      - if total > 0
        %tfooter
          %tr
            %th(colspan="3")
            %th= t('.total_sum') + ':'
            %th.numeric= number_to_currency(total)
  - else
    %i= t '.no_open_orders'

app/views/shared/_order_download_button.html.haml
.btn-group
  = link_to '#', class: "btn #{klass} dropdown-toggle", data: {toggle: 'dropdown'} do
    = t '.title'
    %span.caret
  %ul.dropdown-menu
    %li= order_pdf(order, :groups, t('.group_pdf'))
    %li= order_pdf(order, :articles, t('.article_pdf'))
    %li= order_pdf(order, :matrix, t('.matrix_pdf'))
    %li= order_pdf(order, :fax, t('.fax_pdf'))
    - unless order.stockit?
      %li= link_to t('.fax_txt'), order_path(order, format: :txt), {title: t('.download_file')}
    %li= link_to t('.fax_csv'), order_path(order, format: :csv), {title: t('.download_file')}

app/views/shared/_task_list.haml
%table.table.table-striped
  %thead
    %tr
      %th= heading_helper Task, :due_date
      %th
      %th= heading_helper Task, :name
      %th{:colspan => '2'}
        = t '.who'
        %small= t '.who_hint'
  %tbody
    - tasks.each do |task|
      - done = task.done ? " done" : ""
      %tr{:class => done }
        %td= format_date(task.due_date) unless task.due_date.nil?
        %td
          - if task.periodic?
            %i.icon-repeat{title: t('tasks.repeated')}
        %td= link_to task_title(task), task_path(task)
        %td
          = task_assignments task
          = highlighted_required_users task
        %td
          - if !task.is_accepted?(current_user)
            = link_to t('.accept_task'), accept_task_path(task), method: :post, class: 'btn btn-small'
            = link_to t('.reject_task'), reject_task_path(task), method: :post, class: 'btn btn-small' if task.is_assigned?(current_user)
          - elsif !task.done
            = link_to set_done_task_path(task), method: :post, class: 'btn btn-small',
              title: t('.mark_done') do
              %i.icon-ok= t '.done_q'
          - else
            %i.icon-ok= t '.done'

app/views/shared/_workgroup_members.haml
.well.well-small
  %h4= t '.title'
  #groupMembers.accordion
    - Workgroup.all.each do |workgroup|
      .accordion-group
        .accoridon-heading
          = link_to workgroup.name, "#collapse#{workgroup.id}", data: {toggle: 'collapse', parent: '#groupMembers'}
        %div{id: "collapse#{workgroup.id}", class: 'accordion-body collapse'}
          .accordion-inner
            %ul.unstyled
              - workgroup.users.includes(:groups).natural_order.each do |user|
                %li
                  = show_user(user)
                  %small (#{user.ordergroup.try(:name)})

app/views/shared/alert.js.erb
$('div.container-fluid').prepend('<%= bootstrap_flash_patched %>');