plugins/wiki/config/routes.rb
Rails.application.routes.draw do
  scope '/:foodcoop' do
    resources :pages do
      get :all, on: :collection
      get :version, on: :member
      get :revert, on: :member
      get :diff, on: :member
    end
    get '/wiki/:permalink' => 'pages#show', :as => 'wiki_page' # , :constraints => {:permalink => /[^\s]+/}
    get '/wiki' => 'pages#show', :defaults => { permalink: 'Home' }, :as => 'wiki'
  end
end

plugins/wiki/app/views/pages/_body.html.haml
- content = wikified_body @page.body, @page.title
- toc = generate_toc @page.body

- unless toc.blank? || params[:preview]
  - content_for :sidebar do
    #wikitoc.well.well-small
      %h3= t '.title_toc'
      = toc
= content

plugins/wiki/app/views/pages/_form.html.haml
- if params[:preview]
  %section#wikiContent
    = render 'body'

.row-fluid
  .span8
    = simple_form_for @page do |f|
      = f.hidden_field :lock_version
      = f.input :title, input_html: {class: 'input-xxlarge'}
      = f.input :body, input_html: {class: 'input-xxlarge', rows: 20}
      = f.input :parent_id, as: :select, collection: parent_pages_to_select(@page)
      .form-actions
        = button_tag :name => 'preview', class: 'btn' do
          %i.icon-search= t '.preview'
        = button_tag class: 'btn' do
          %i.icon-save= t 'ui.save'
        = link_to t('ui.or_cancel'), @page

  .span4
    %h3(style='margin-top: 0')= t '.help.title'
    %table.table
      %tbody
        %tr
          %td(colspan=2)
            %b= t '.help.section_character'
        %tr
          %td
            %i= t '.help.italic'
          %td
            %pre
              ''#{t '.help.italic'}''<br />
        %tr
          %td
            %b= t '.help.bold'
          %td
            %pre '''#{t '.help.bold'}'''<br />
        %tr
          %td= t '.help.noformat'
          %td
            %pre &lt;nowiki&gt;#{t '.help.text'}&lt;/nowiki&gt;
        %tr
          %td(colspan=2)
            %b= t '.help.section_block'
        %tr
          %td= t '.help.headings'
          %td
            %pre
              \== #{t '.help.heading', level: 1} == <br>
              \=== #{t '.help.heading', level: 2} === <br>
              \==== #{t '.help.heading', level: 3} ==== <br>
        %tr
          %td= t '.help.unordered_list'
          %td
            %pre
              * #{t '.help.list_item_1'} <br>
              * #{t '.help.list_item_2'}
        %tr
          %td= t '.help.ordered_list'
          %td
            %pre
              \# #{t '.help.list_item_1'} <br>
              \# #{t '.help.list_item_2'}
        %tr
          %td(colspan=2)
            %b= t '.help.section_link'
        %tr
          %td= t '.help.wiki_links'
          %td
            %pre
              [[#{t '.help.wiki_link_ex'}]]
        %tr
          %td= t '.help.external_links'
          %td
            %pre
              [http://example.net #{t '.help.external_link_ex'}]
        %tr
          %td= t '.help.image_links'
          %td
            %pre
              [[Image:http://example.net/image.jpg|#{t '.help.image_link_title'}]]
        %tr
          %td(colspan=2)
            %b= t '.help.section_more'
        %tr
          %td(colspan=2)
            %ul
              %li!= link_to t('.help.link_table'), '//www.mediawiki.org/wiki/Help:Tables', target: '_blank'
              %li!= link_to t('.help.link_variables'), page_path('Help:Foodsoft_variables'), target: '_blank'
              %li!= link_to t('.help.link_lists'), '//www.mediawiki.org/wiki/Help:Lists', target: '_blank'
              %li!= link_to t('.help.link_templates'), '//www.mediawiki.org/wiki/Help:Templates', target: '_blank'

plugins/wiki/app/views/pages/_page_list_item.html.haml
-ident = 20 * level
%tr
  %td{:style => "padding-left: #{ident}px"}
    = link_to page.title, wiki_page_path(page.permalink)
  %td #{show_user page.user} (#{format_datetime_timespec(page.updated_at, t('.date_format'))})
-if siteMap == 1
  -for child in page.children.all
    = render :partial => 'page_list_item', :locals => {:page => child, :level => level+1, :siteMap => 1}

plugins/wiki/app/views/pages/_site_map.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= t 'pages.title'
      %th= t 'pages.last_updated'
    - homepage = Page.find_by_permalink('Home')
    - unless homepage.nil?
      = render :partial => 'page_list_item', :locals => {:page => homepage, :level => 0, :siteMap => 1}
  %tbody
    - for page in @pages
      - if page.id != homepage.try(:id) && !page.parent_id?
        = render :partial => 'page_list_item', :locals => {:page => page, :level => 0, :siteMap => 1}

plugins/wiki/app/views/pages/_title_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th= sort_link_helper t('pages.title'), "title", :remote => false
      %th= sort_link_helper t('pages.last_updated'), "last_updated", :remote => false
  %tbody
    - for page in @pages
      = render :partial => "page_list_item", :locals => {:page => page, :level => 0, :siteMap => 0}

plugins/wiki/app/views/pages/all.html.haml
- title t('.title'), false

- content_for :sidebar do
  = link_to t('.new_page'), new_page_path, class: 'btn btn-primary'

.navbar
  .navbar-inner
    %ul.nav
      %li= link_to t('.title_list'), all_pages_path(:view => 'title_list')
      %li= link_to t('.site_map'), all_pages_path(:view => 'site_map')
      %li= link_to image_tag('icons/feed-icon-14x14.png', :alt => 'RSS Feed'), all_pages_rss_url
    = form_tag all_pages_path, method: :get, class: 'form-search pull-right' do
      = text_field_tag :name, params[:name], class: 'input-medium search-query',
        placeholder: t('.search.placeholder')
      = submit_tag t('.search.action'), class: 'btn'

= render @partial

plugins/wiki/app/views/pages/diff.html.haml
- title t('.title', title: @page.title, old: @old_version.lock_version, new: @new_version.lock_version)

%style= Diffy::CSS
= raw @diff

%hr
= link_to t('ui.back'), 'javascript:history.go(-1)', class: 'btn btn-primary'

plugins/wiki/app/views/pages/edit.html.haml
- title t('.title')

= render 'form'

plugins/wiki/app/views/pages/new.html.haml
- title t('.title')

= render 'form'

plugins/wiki/app/views/pages/show.html.haml
- title @page.title, false

- content_for :sidebar do
  %p
    = link_to edit_page_path(@page), class: 'btn btn-primary' do
      %i.icon-edit= t '.edit'
  .well.well-small
    %ul.nav.nav-list
      %li
      %li= link_to t('.versions', count: @page.versions.count), "#versions", 'data-toggle-this' => '#versions'
      - unless @page.children.empty?
        %li= link_to t('.subpages'), "#subpages", 'data-toggle-this' => '#subpages'

  #versions.well.well-small{:style => "display:none"}
    = form_tag diff_page_path(@page), :method => :get do
      %h3= t '.title_versions'
      %ul.unstyled
        - @page.versions.reverse.each_with_index do |version, index|
          %li
            = radio_button_tag :old, version.lock_version, index == 1
            = radio_button_tag :new, version.lock_version, index == 0
            = link_to I18n.l(version.updated_at, :format => t('.date_format')), version_page_path(@page, :version => version.lock_version)
            = "(#{show_user(User.find_by_id(version.updated_by))})"
      = submit_tag t('.diff'), class: 'btn'

  - unless @page.children.empty?
    #subpages.well.well-small{:style => "display:none"}
      %h3= t '.subpages'
      %ul.unstyled
        - @page.children.each do |page|
          %li= link_to_wikipage(page)

%ul.breadcrumb
  %li
    = link_to_wikipage_by_permalink("Home", "Foodcoop-Wiki")
    %span.divider /
  - for page in @page.ancestors.reverse
    %li
      = link_to_wikipage(page)
      %span.divider /
  %li.active= @page.title


#wikiContent
  .page-header
    %h1= @page.title
  = render :partial => 'body'

%hr.clear/
%p
  = link_to edit_page_path(@page), class: 'btn btn-primary' do
    %i.icon-edit= t '.edit'
  = link_to t('.delete'), @page, class: 'btn btn-danger', :method => :delete,
    :data => {:confirm => t('.delete_confirm')}
  != '| ' + t('.last_updated', user: show_user(@page.user), when: format_datetime(@page.updated_at))

plugins/wiki/app/views/pages/variables.html.haml
- title t '.title'

%p= t '.description'

%table.table.table-hover
  %thead
    %tr
      %th= t '.variable'
      %th= t '.value'
  %tbody
    - @variables.each do |key, value|
      %tr
        %td
          %tt= "{{#{key}}}"
        %td
          = value

plugins/wiki/app/views/pages/version.html.haml
- title t('.title', title: @page.title, version: @version.lock_version)

- content_for :sidebar do
  %h3= t '.title_version'
  %b= "#{format_datetime_timespec(@version.updated_at, t('.date_format'))}"
  %ul
    %li= t '.author', user: show_user(User.find_by(id: @version.updated_by))
    %li= link_to t('.view_current'), wiki_page_path(:permalink => @page.permalink)
    %li= link_to t('.revert'), revert_page_path(@page, :version => @version.lock_version)

= wikified_body @version.body