config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'order_comments/new'

  get 'comments/new'

  get 'sessions/new'

  root to: 'sessions#redirect_to_foodcoop', as: nil

  scope '/:foodcoop' do
    use_doorkeeper

    # Root path
    root to: 'home#index'

    ########### Sessions

    get   '/login' => 'sessions#new', as: 'login'
    get   '/logout' => 'sessions#destroy', as: 'logout'
    get   '/login/forgot_password' => 'login#forgot_password', as: :forgot_password
    post  '/login/reset_password' => 'login#reset_password', as: :reset_password
    get   '/login/new_password' => 'login#new_password', as: :new_password
    patch '/login/update_password' => 'login#update_password', as: :update_password
    match '/login/accept_invitation/:token' => 'login#accept_invitation', as: :accept_invitation, via: %i[get post]
    resources :sessions, only: %i[new create destroy]

    get '/foodcoop.css' => 'styles#foodcoop', as: 'foodcoop_css'

    ########### User specific

    get   '/home/profile', as: 'my_profile'
    get   '/home/reference_calculator'
    patch '/home/update_profile', as: 'update_profile'
    get   '/home/ordergroup' => 'home#ordergroup', as: 'my_ordergroup'
    post  '/home/cancel_membership' => 'home#cancel_membership', as: 'cancel_membership'

    ############ Orders, ordering

    resources :orders do
      member do
        post :finish
        post :add_comment
        post :send_result_to_supplier

        get :receive
        post :receive

        get :receive_on_order_article_create
        get :receive_on_order_article_update
      end

      resources :order_articles
    end

    resources :pickups, only: [:index] do
      post :document, on: :collection
    end

    resources :group_orders do
      get :archive, on: :collection
    end

    resources :group_order_articles

    resources :order_comments, only: %i[new create]

    ############ Foodcoop orga

    resources :invites, only: %i[new create]

    resources :tasks do
      collection do
        get :user
        get :archive
        get :workgroup
      end
      member do
        post :accept
        post :reject
        post :set_done
      end
    end

    namespace :foodcoop do
      root to: 'users#index'

      resources :users, only: [:index]

      resources :ordergroups, only: [:index]

      resources :workgroups, only: %i[index edit update]
    end

    ########### Article management

    resources :stock_takings do
      collection do
        get :new_on_stock_article_create
      end
    end

    resources :stock_articles, controller: 'stockit' do
      get :copy
      collection do
        get :derive

        get :index_on_stock_article_create
        get :index_on_stock_article_update

        get :show_on_stock_article_update
      end
    end

    resources :suppliers do
      get :shared_suppliers, on: :collection

      resources :deliveries do
        collection do
          post :add_stock_change

          get :form_on_stock_article_create
          get :form_on_stock_article_update
        end
      end

      resources :articles do
        get :copy
        collection do
          post :update_selected
          get :edit_all
          post :update_all
          get :upload
          post :parse_upload
          post :create_from_upload
          get :shared
          get :import
          post :sync
          post :update_synchronized
        end
      end
    end

    resources :article_categories

    ########### Finance

    namespace :finance do
      root to: 'base#index'

      resources :order, controller: 'balancing', path: 'balancing' do
        member do
          get :update_summary
          get :edit_note
          put :update_note
          get :edit_transport
          put :update_transport

          get :confirm
          post :close
          patch :close_direct

          get :new_on_order_article_create
          get :new_on_order_article_update
        end

        post :close_all_direct_with_invoice, on: :collection
      end

      resources :invoices do
        get :form_on_supplier_id_change, on: :collection
        get :unpaid, on: :collection
        delete 'delete_attachment/:attachment_id', to: 'invoices#delete_attachment', as: 'delete_attachment', on: :member
      end

      resources :links, controller: 'financial_links', only: %i[create show] do
        collection do
          get :incomplete
        end
        member do
          get :index_bank_transaction
          put 'bank_transactions/:bank_transaction', action: 'add_bank_transaction', as: 'add_bank_transaction'
          delete 'bank_transactions/:bank_transaction', action: 'remove_bank_transaction', as: 'remove_bank_transaction'

          get :index_financial_transaction
          put 'financial_transactions/:financial_transaction', action: 'add_financial_transaction',
                                                               as: 'add_financial_transaction'
          delete 'financial_transactions/:financial_transaction', action: 'remove_financial_transaction',
                                                                  as: 'remove_financial_transaction'

          get :index_invoice
          put 'invoices/:invoice', action: 'add_invoice', as: 'add_invoice'
          delete 'invoices/:invoice', action: 'remove_invoice', as: 'remove_invoice'

          get :new_financial_transaction
          post :create_financial_transaction
        end
      end

      resources :ordergroups, only: [:index] do
        resources :financial_transactions, as: :transactions
      end
      resources :financial_transactions, as: :foodcoop_financial_transactions, path: 'foodcoop/financial_transactions',
                                         only: %i[index new create]
      get :transactions, controller: :financial_transactions, action: :index_collection
      delete 'transactions/:id', controller: :financial_transactions, action: :destroy, as: :transaction

      get 'transactions/new_collection' => 'financial_transactions#new_collection', as: 'new_transaction_collection'
      post 'transactions/create_collection' => 'financial_transactions#create_collection',
           as: 'create_transaction_collection'

      resources :bank_accounts, only: [:index] do
        member do
          get :assign_unlinked_transactions
          get :import
          post :import
        end

        resources :bank_transactions, as: :transactions
      end

      resources :bank_transactions, only: %i[index show]
    end

    ########### Administration

    namespace :admin do
      root to: 'base#index'

      resources :finances, only: [:index] do
        get :update_bank_accounts, on: :collection
        get :update_bank_gateways, on: :collection
        get :update_transaction_types, on: :collection
        get :update_supplier_categories, on: :collection
      end

      resources :bank_accounts
      resources :bank_gateways
      resources :financial_transaction_classes
      resources :financial_transaction_types
      resources :supplier_categories

      resources :users do
        post :restore, on: :member
        post :sudo, on: :member
      end

      resources :workgroups do
        get :memberships, on: :member
      end

      resources :ordergroups do
        get :memberships, on: :member
      end

      resources :mail_delivery_status, only: %i[index show destroy] do
        delete :index, on: :collection, action: :destroy_all
      end

      resource :config, only: %i[show update] do
        get :list
      end
    end

    ############## API

    namespace :api do
      namespace :v1 do
        resource :config, only: [:show]
        resource :navigation, only: [:show]

        namespace :user do
          root to: 'users#show'
          get :financial_overview, to: 'ordergroup#financial_overview'
          resources :financial_transactions, only: %i[index show create]
          resources :group_order_articles
        end

        resources :financial_transaction_classes, only: %i[index show]
        resources :financial_transaction_types, only: %i[index show]
        resources :financial_transactions, only: %i[index show]
        resources :orders, only: %i[index show]
        resources :order_articles, only: %i[index show]
        resources :group_order_articles
        resources :article_categories, only: %i[index show]
      end
    end

    ############## The rest

    resources :users, only: [:index]
  end # End of /:foodcoop scope
end
# rubocop:enable Metrics/BlockLength

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # unaccepted tasks
    @unaccepted_tasks = Task.order(:due_date).unaccepted_tasks_for(current_user)
    # task in next week
    @next_tasks = Task.order(:due_date).next_assigned_tasks_for(current_user)
    # count tasks with no responsible person
    # tasks for groups the current user is not a member are ignored
    @unassigned_tasks = Task.order(:due_date).next_unassigned_tasks_for(current_user)
  end

  def profile; end

  def reference_calculator
    if current_user.ordergroup
      @types = FinancialTransactionType.with_name_short.order(:name)
      @bank_accounts = @types.includes(:bank_account).map(&:bank_account).uniq.compact
      @bank_accounts = [BankAccount.last] if @bank_accounts.empty?
    else
      redirect_to root_url, alert: I18n.t('group_orders.errors.no_member')
    end
  end

  def update_profile
    if @current_user.update(user_params)
      @current_user.ordergroup.update(ordergroup_params) if ordergroup_params
      session[:locale] = @current_user.locale
      redirect_to my_profile_url, notice: I18n.t('home.changes_saved')
    else
      render :profile
    end
  end

  def ordergroup
    @user = @current_user
    @ordergroup = @user.ordergroup

    if @ordergroup.nil?
      redirect_to root_path, alert: I18n.t('home.no_ordergroups')
    else

      @ordergroup = Ordergroup.include_transaction_class_sum.find(@ordergroup.id)

      sort = if params['sort']
               case params['sort']
               when 'date' then 'created_on'
               when 'note'   then 'note'
               when 'amount' then 'amount'
               when 'date_reverse' then 'created_on DESC'
               when 'note_reverse' then 'note DESC'
               when 'amount_reverse' then 'amount DESC'
               end
             else
               'created_on DESC'
             end

      @financial_transactions = @ordergroup.financial_transactions.visible.page(params[:page]).per(@per_page).order(sort)
      if params[:query].present?
        @financial_transactions = @financial_transactions.where('financial_transactions.note LIKE ?',
                                                                "%#{params[:query]}%")
      end

    end
  end

  # cancel personal memberships direct from the myProfile-page
  def cancel_membership
    membership = if params[:membership_id]
                   @current_user.memberships.find(params[:membership_id])
                 else
                   @current_user.memberships.find_by_group_id!(params[:group_id])
                 end
    membership.destroy
    redirect_to my_profile_path, notice: I18n.t('home.ordergroup_cancelled', group: membership.group.name)
  end

  protected

  def user_params
    params
      .require(:user)
      .permit(:first_name, :last_name, :email, :phone,
              :password, :password_confirmation).merge(params[:user].slice(:settings_attributes))
  end

  def ordergroup_params
    return unless params[:user][:ordergroup]

    params.require(:user).require(:ordergroup).permit(:contact_address)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_apple_bar.html.haml
= t '.points', points: apple_bar.apples
.progress
  %div{class: "bar bar-#{apple_bar.group_bar_state}", style: "width: #{apple_bar.group_bar_width}%"}

%span.description
  = t '.desc', amount: number_to_currency(apple_bar.mean_order_amount_per_job, :precision=>0)
  - if FoodsoftConfig[:stop_ordering_under].present?
    %strong= t('.warning', threshold: FoodsoftConfig[:stop_ordering_under])
  = link_to t('.more_info'), FoodsoftConfig[:applepear_url], target: '_blank'

app/views/home/_start_nav.haml
.well.well-small
  %h3= t '.title'
  %ul.nav.nav-list
    %li.nav-header= t '.foodcoop'
    - unless FoodsoftConfig[:disable_members_overview]
      %li= link_to t('.members'), foodcoop_users_path
    %li= link_to t('.tasks'), user_tasks_path

    - has_ordergroup = !@current_user.ordergroup.nil?
    - has_orders_role = @current_user.role_orders?
    - if has_ordergroup || has_orders_role
      %li.nav-header= t '.orders.title'
      - if has_ordergroup
        %li= link_to t('.orders.overview'), group_orders_path
      - if has_orders_role
        %li= link_to t('.orders.end'), :controller => 'orders'
    // Articles
    - if @current_user.role_article_meta? || @current_user.role_suppliers?
      %li.nav-header= t '.products.title'
      %li= link_to t('.products.edit'), suppliers_path
      %li= link_to t('.products.edit_stock'), :controller => 'stockit'
      %li= link_to t('.products.edit_suppliers'), suppliers_path

    // Finance
    - if @current_user.role_finance?
      %li.nav-header= t '.finances.title'
      %li= link_to t('.finances.accounts'), finance_new_transaction_collection_path
      %li= link_to t('.finances.settle'), finance_root_path

    // Administration
    - if @current_user.role_admin?
      %li.nav-header= t '.admin'
      %li= link_to t('.new_ordergroup'), new_admin_ordergroup_path
      %li= link_to t('.new_user'), new_admin_user_path

app/views/home/index.html.haml
- title t('.title'), false

- content_for(:sidebar) do
  = render :partial => 'start_nav'

-# placeholder deface to add content using erb[silent]:contains()
- '<dashboard_top_mark>'

- unless @unaccepted_tasks.empty? && @next_tasks.empty?
  %section.row-fluid
    - unless @next_tasks.empty?
      .span3.well
        %h4= t '.your_tasks'
        %dl
          - @next_tasks.each do |task|
            %dt= l task.due_date, format: t('.due_date_format')
            %dd= link_to task.name, task_path(task)
    - unless @unaccepted_tasks.empty?
      .span3.well
        %h4= t '.tasks_move.title'
        = t '.tasks_move.desc'
        = link_to t('.tasks_move.action'), user_tasks_path

- if @unassigned_tasks.size > 0
  %section
    %h2
      = t '.tasks_open.title'
      %small
        = link_to tasks_path do
          = t '.tasks_open.view_all'
          %i.icon.icon-chevron-right
    = render 'shared/task_list', tasks: @unassigned_tasks

- if current_user.ordergroup
  = render :partial => 'shared/open_orders', :locals => {:ordergroup => current_user.ordergroup}

// Stats
- if current_user.ordergroup and FoodsoftConfig[:use_apple_points]
  %section
    %h2= t '.ordergroup.title'
    = render :partial => "apple_bar", :locals => {:apple_bar => AppleBar.new(current_user.ordergroup)}

-# placeholder deface to add content using erb[silent]:contains()
- '<dashboard_middle_mark>'

- if current_user.ordergroup

  // Ordergroup overview
  %section
    %h2= t '.my_ordergroup.title'
    %p
      %b= current_user.ordergroup.name
      = ' | '
      - if FoodsoftConfig[:charge_members_manually]
        = heading_helper(Ordergroup, :account_balance) + ':'
        = number_to_currency(current_user.ordergroup.account_balance)
      - else
        = heading_helper(Ordergroup, :available_funds) + ':'
        = number_to_currency(current_user.ordergroup.get_available_funds)
      %small= t '.my_ordergroup.last_update', when: distance_of_time_in_words(Time.now, current_user.ordergroup.account_updated)
      %h3
        = t '.my_ordergroup.transactions.title'
        %small
          = link_to my_ordergroup_path do
            = t '.my_ordergroup.transactions.view'
            %i.icon.icon-chevron-right
          - '<dashboard_ordergroup_mark>'
      %table.table.table-striped
        - financial_transactions = current_user.ordergroup.financial_transactions.visible.includes(:financial_transaction_type, :user).limit(5).order(created_on: :desc)
        - with_payment = financial_transactions.with_payment_plugin.any?
        %tr
          %th= heading_helper FinancialTransaction, :created_on
          %th= heading_helper FinancialTransaction, :user
          - if FinancialTransactionType.has_multiple_types
            %th= heading_helper FinancialTransaction, :financial_transaction_type
          %th= heading_helper FinancialTransaction, :note
          - if with_payment
            %th= heading_helper FinancialTransaction, :payment_state
          - FinancialTransactionClass.sorted.each do |fc|
            %th
              = fc.display
        - for ft in financial_transactions
          %tr
            %td= format_time(ft.created_on)
            %td= h(show_user(ft.user))
            - if FinancialTransactionType.has_multiple_types
              %td= h(ft.financial_transaction_type.name)
            %td= h(render "finance/financial_transactions/order_note", financial_transaction:ft, with_grouporder_link: true)
            - if with_payment
              %td= h(ft.payment_state)
            - FinancialTransactionClass.sorted.each do |fc|
              %td.numeric{style: 'width:5em'}
                - if ft.financial_transaction_type.financial_transaction_class == fc
                  = format_currency(ft.amount)

-# placeholder deface to add content using erb[silent]:contains()
- '<dashboard_bottom_mark>'

app/views/home/ordergroup.html.haml
- title t('.title'), false

.row-fluid
  .span4
    %h2= @ordergroup.name
    .well
      - unless @ordergroup.description.blank?
        %p= @ordergroup.description
      %p
        %b= heading_helper(Ordergroup, :account_balance) + ':'
        = number_to_currency(@ordergroup.account_balance)
      - unless FoodsoftConfig[:charge_members_manually]
        %p
          %b= heading_helper(Ordergroup, :available_funds) + ':'
          = number_to_currency(@ordergroup.get_available_funds())
      - if FinancialTransactionClass.has_multiple_classes
        - FinancialTransactionClass.sorted.each do |c|
          %p
            %b= c.display + ':'
            = number_to_currency(@ordergroup["sum_of_class_#{c.id}"])
      %p
        %b= heading_helper(Ordergroup, :user_tokens) + ':'
        = @ordergroup.memberships.map{|m| show_user m.user}.join(', ')
      - unless FoodsoftConfig[:disable_invite]
        = link_to t('.invite'), new_invite_path(:id => @ordergroup), :remote => true, class: 'btn btn-primary'
      - '<home_ordergroup_well_mark>'
  .span8
    %h2= t('.account_summary')
    .well.well-small
      = form_tag my_ordergroup_path, :method => :get, :remote => true,
        'data-submit-onchange' => true, class: 'form-search' do
        = text_field_tag :query, params[:query], class: 'input-medium search-query',
          placeholder: t('.search')
    #transactions= render "finance/financial_transactions/transactions", with_csv: false, with_grouporder_links: true

app/views/home/ordergroup.js.haml
$('#transactions').html('#{j(render("finance/financial_transactions/transactions"))}');

app/views/home/profile.html.haml
- title t('.title'), false

.row-fluid
  .span7
    %h3
      = h(t('.user.title', user: show_user))
      %small= t '.user.since', when: distance_of_time_in_words(Time.now, @current_user.created_on)
    = simple_form_for(@current_user, :url => update_profile_path) do |f|
      = render :partial => 'shared/user_form_fields', :locals => {:f => f, :password_autocomplete => 'store-only', with_address: true}
      .form-actions
        = submit_tag t('ui.save'), class: 'btn'

  .span5
    - if @current_user.ordergroup
      %h3= User.human_attribute_name(:ordergroup, count: 1)
      %table.table.table-striped
        %tr
          %td
            - if @current_user.ordergroup.users.count > 1
              %strong= @current_user.ordergroup.name + ':'
              = @current_user.ordergroup.users.map{|u| show_user u}.join(', ')
            - else
              = @current_user.ordergroup.name
          %td.right
            - unless FoodsoftConfig[:disable_invite]
              = link_to t('.groups.invite'), new_invite_path(id: @current_user.ordergroup),
                        remote: true, class: 'btn btn-success btn-small'
    - if @current_user.workgroups.any?
      %h3= User.human_attribute_name(:workgroup, count: 2)
      %table.table.table-striped
        - @current_user.workgroups.each do |workgroup|
          %tr
            %td= workgroup.name
            %td.right
              = link_to t('.groups.cancel'), cancel_membership_path(group_id: workgroup),
                        :data => {confirm: t('.groups.cancel_confirm')}, method: :post,
                        class: 'btn btn-danger btn-small'

app/views/home/reference_calculator.haml
- title t('.title')

- content_for :javascript do
  :javascript
    $(function() {
      var default_bank_account = $('p[data-text]').attr('data-text');

      function update() {
        var items = {};
        var hide_placeholder = false;

        $('input[data-has-name-short]').each(function() {
          var bank_account = $(this).attr('data-bank-account') || default_bank_account;
          var name = $(this).attr('name');
          var value = Math.round(parseFloat($(this).val()) * 100) / 100;
          if (value > 0) {
            var item = items[bank_account];
            if (!item) {
              items[bank_account] = item = { amount: 0, values: {} };
            }

            item.amount += value;
            item.values[name] = value;
            hide_placeholder = true;
          }
        });

        $('p[data-text]').each(function() {
          var ele = $(this);
          var bank_account = ele.attr('data-text');
          var item = items[bank_account];
          console.dir(item);
          if (item) {
            ele.show();
            ele.find('.amount').text(item.amount.toFixed(2));
            ele.find('.reference').text((#{raw BankTransactionReference.js_code_for_user(@current_user)})(item.values));
          } else {
            ele.hide();
          }
        });

        if (hide_placeholder) {
          $('#placeholder').hide();
        } else {
          $('#placeholder').show();
        }
      }

      $(document).on('input', 'input[data-has-name-short]', update);
      update();
    });

= form_tag finance_create_transaction_collection_path do
  %p
    %table#ordergroups
      %thead
        %tr
          %th= t('.transaction_types_headline')
          %th= heading_helper FinancialTransaction, :amount
      %tbody
        - for t in @types
          %tr
            %td= "#{t.name} (#{t.name_short}):"
            %td
              .input-prepend
                %span.add-on= t 'number.currency.format.unit'
                = text_field_tag t.name_short, nil, class: 'input-small',
              'data-has-name-short' => true, 'data-bank-account' => t.bank_account.try(:id),
              step: 0.01, type: :number
  %p#placeholder
    = t('.placeholder')
  - for ba in @bank_accounts
    %p{'data-text' => ba.id}
      = t('.text0')
      %b.amount= '?'
      %b= t 'number.currency.format.unit'
      = t('.text1')
      %b.reference= '?'
      = t('.text2')
      %b= format_iban ba.iban